-- Feel free to modify this file to match your development goal.
-- Here we only create 3 tables for demo purpose.


CREATE TABLE Users (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255),
    lastname VARCHAR(255),
    balance FLOAT NOT NULL,
    address VARCHAR(255) NOT NULL
);


CREATE TABLE Charities (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userid INT NOT NULL REFERENCES Users(id),
    name VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    description VARCHAR NOT NULL
);


-- Charity(charity_user_id, org_id)


CREATE TABLE Products (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    starting_bid DECIMAL(12,2) NOT NULL,
    buy_now DECIMAL(12,2) NOT NULL,
    available BOOLEAN DEFAULT TRUE,
    catergory VARCHAR(255),
    expiration timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    image VARCHAR NOT NULL,
    rating DECIMAL(12,2) NOT NULL
);


CREATE TABLE Sells (
    charityId INT NOT NULL REFERENCES Charities(id),
    productId INT NOT NULL REFERENCES Products(id),
    PRIMARY KEY(charityId, productId)
);




CREATE TABLE Purchases (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    --Should I create a name column?
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    time_purchased timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);


CREATE TABLE Cart (
    buyer_id           INT NOT NULL REFERENCES Users(id),
    product_id         INT NOT NULL REFERENCES Products(id)
);


CREATE TABLE Orders (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    purchaseId INT NOT NULL REFERENCES Purchases(id),
    productName VARCHAR(255) UNIQUE NOT NULL,
    buyerId INT NOT NULL REFERENCES Users(id),
    sellerId INT NOT NULL REFERENCES Charities(id),
    date_placed timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    total_cost DECIMAL(12,2) NOT NULL,
    status BOOLEAN DEFAULT FALSE
    --status VARCHAR(255) NOT NULL DEFAULT 'pending', -- Example values: pending, paid, shipped, delivered, cancelled
    --tracking_number VARCHAR(255), -- Nullable because it might not exist at order creation
    --address_id INT, -- If you have an address table, you would reference it here
    --payment_id INT -- If you have a payment methods table, it would be referenced here
    -- Further normalization can be done by having a separate OrderDetails table to track individual product purchases
);




CREATE TABLE Wishlist (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    time_added timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);


CREATE TABLE Reviews (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    date_posted timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    feedback TEXT NOT NULL,
    upvote INT DEFAULT 0,
    CONSTRAINT only_one_review_per_product_review UNIQUE (uid, pid)
);


CREATE TABLE Reviewtransactions (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    review_id INT NOT NULL REFERENCES Reviews(id) ON DELETE CASCADE,
    uid INT NOT NULL REFERENCES Users(id),
    time_upvoted timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    amount decimal(10, 2) NOT NULL CHECK (amount = 1 OR amount = -1),
    CONSTRAINT only_one_vote_per_product_review UNIQUE (review_id, uid)
);


CREATE OR REPLACE FUNCTION update_reviews_when_upvote()
    RETURNS trigger AS
$$
BEGIN


    IF (TG_OP = 'UPDATE') THEN
        UPDATE Reviews
        SET upvote= upvote - old.amount + new.amount
        where id = new.review_id;
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        UPDATE Reviews
        SET upvote= upvote + NEW.amount
        where id = new.review_id;
        RETURN NEW;
    end if;
END;
$$ LANGUAGE plpgsql VOLATILE;


CREATE TRIGGER update_reviews_when_upvote_trigger
    After INSERT OR UPDATE
    ON Reviewtransactions
    FOR EACH ROW
EXECUTE PROCEDURE update_reviews_when_upvote();




CREATE TABLE Bids (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    amount DECIMAL(12,2) NOT NULL,
    bidtime timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);

CREATE TABLE MessageThreads (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INT NOT NULL REFERENCES Products(id),
    subject VARCHAR(255)
);

CREATE TABLE Messages (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    thread_id INT REFERENCES MessageThreads(id),
    sender_id INT NOT NULL REFERENCES Users(id),
    receiver_id INT NOT NULL REFERENCES Users(id),
    message TEXT NOT NULL,
    time_sent timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    read BOOLEAN DEFAULT FALSE,
    reply TEXT,
    reply_time_sent timestamp without time zone,
    reply_read BOOLEAN DEFAULT FALSE
);



ALTER TABLE Cart ADD COLUMN is_favorite BOOLEAN DEFAULT FALSE;




